### ISSUE TITLE
provide requirements-frozen.txt file

### ISSUE THREAD

**Issue by etam** [cryptobench/golem-provider-benchmark#8]
I like how your `requirements.txt` specifies only direct dependencies.

As a devops I need a reproducible method of deploying this software. I'd like you to create and maintain `requirements-frozen.txt` file either manually (`pip freeze > requirements-frozen.txt`) or with script like https://pypi.org/project/freeze-requirements/

**Comment by cryptobench** [comment]
I've added a frozen requirements file to the repo.
